import type { Pattern } from "../lib/validation/stitch";
import { makeGrid } from "../utils/pattern-grid";

export const PATTERNS: Pattern[] = [
  {
    id: "bear",
    name: "栗子小熊",
    subtitle: "一杯茶的温柔时间",
    difficulty: "入门",
    size: 24,
    minutes: 35,
    grid: makeGrid("bear"),
  },
  {
    id: "sunrise",
    name: "山野日出",
    subtitle: "把清晨缝进布里",
    difficulty: "轻松",
    size: 24,
    minutes: 42,
    grid: makeGrid("sunrise"),
  },
  {
    id: "tulip",
    name: "粉色郁金香",
    subtitle: "春天的一小束",
    difficulty: "入门",
    size: 24,
    minutes: 28,
    grid: makeGrid("tulip"),
  },
  {
    id: "bird",
    name: "蓝羽小鸟",
    subtitle: "窗边停留的朋友",
    difficulty: "轻松",
    size: 24,
    minutes: 38,
    grid: makeGrid("bird"),
  },
  {
    id: "cup",
    name: "草莓茶杯",
    subtitle: "甜点时间",
    difficulty: "进阶",
    size: 24,
    minutes: 48,
    grid: makeGrid("cup"),
  },
  {
    id: "cabin",
    name: "月夜小屋",
    subtitle: "森林深处有灯光",
    difficulty: "进阶",
    size: 24,
    minutes: 52,
    grid: makeGrid("cabin"),
  },
  {
    id: "cat",
    name: "橘猫伸懒腰",
    subtitle: "慢吞吞的午后",
    difficulty: "轻松",
    size: 24,
    minutes: 40,
    grid: makeGrid("cat"),
  },
  {
    id: "lemon",
    name: "柠檬枝",
    subtitle: "明亮又清新的夏日",
    difficulty: "入门",
    size: 24,
    minutes: 30,
    grid: makeGrid("lemon"),
  },
  {
    id: "mushroom",
    name: "红帽蘑菇",
    subtitle: "雨后森林来信",
    difficulty: "轻松",
    size: 24,
    minutes: 36,
    grid: makeGrid("mushroom"),
  },
  {
    id: "whale",
    name: "深海小鲸",
    subtitle: "带着气泡去旅行",
    difficulty: "进阶",
    size: 24,
    minutes: 45,
    grid: makeGrid("whale"),
  },
];
